#!/bin/bash

echo "running testing script"

for i in {100..2000..100}
  do 
    ./test_Driver_optimized  $i >>log.txt
	./test_Driver $i >> log2.txt
 done

if [ "$1" = g ]
then
   echo "plotting results"
   gnuplot graph.gnu
fi
