#!/bin/bash

echo "running testing script"

#remove old logs everytime we run
rm log.txt log2.txt log3.txt mpi_log.txt


for i in {200..1000..200}
  do 
   ./test_Driver_optimized  $i >>log.txt
	./test_Driver $i >> log2.txt
   ./mmult_omp_timing $i >> log3.txt
   mpiexec -f ~/hosts -n 5 ./mmult_mpi $i >> mpi_log.txt
 done

 for i in {200..3000..200}
  do 
   mpiexec -f ~/hosts -n 7 ./mmult_mpi $i >> mpi_log5.txt
   mpiexec -f ~/hosts -n 10 ./mmult_mpi $i >> mpi_log6.txt
   mpiexec -f ~/hosts -n 20 ./mmult_mpi $i >> mpi_log7.txt
 done


if [ "$1" = g ]
then
   echo "plotting results"
   gnuplot graph.gnu
fi
